language: rust
sudo: false
cache: cargo

notifications:
  email: false

branches:
  only:
    # Enable building pull requests.
    - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

matrix:
  include:
    - rust: 1.20.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - |
      set -e
      cargo build --verbose &&
      cargo test --verbose
