[package]
name = "petgraph-graphml"
version = "1.0.0"
authors = ["jonasbb"]

description = "GraphML "
documentation = "https://docs.rs/petgraph-graphml/"
repository = "https://github.com/jonasbb/petgraph-graphml"
# readme = "README.md"
keywords = ["graphml", "petgraph"]
license = "MIT/Apache-2.0"

[dependencies]
petgraph = "0.4.0"
xml-rs = "0.7.0"
